const DEFAULT_PAIRS=[["Adri Salaverría","María Salaverría"],["Albert Cabezas","Ramon Romero"],["Mauro Lenhardi","Roger Juanola"],["Julia Serrano","Juan Sobreroca"],["Alvaro Palou","Pepe Palou"],["Lluís Aymami","Diego Salvo"],["Marc Muntané","Alex Sanchez"],["Arnau Costa","Otger Costa"],["Maurici Monguet","Marius Alcala"],["Marc Balcells","Manel Villegas"],["Lluís Cabezas","Xavi Palou Pare"],["Sergi Ripollés","Ferran Cabezas"],["Edu Llop","David Grau"],["Jordi Civit","Laura Soler Pericas"],["Toni Civit","Jordi Balcells Senior"],["Pol Gaynes","Gerard Civit"],["Claudia Balcells","Jemi Recasens"],["Blanca Josep","Sara Vidal"],["Ian Dameson","Eloi de la Torre"],["Paula Quilez","Marc Cid"],["Carlota Domínguez","Joel Socias"],["Pau Tetas","Santi Torné"],["Guillem Tost","Joan Valette"],["Albert Civit","Ramon Maria Nadal"],["Pol Mitjavila","Martí Coma"],["Claudia Mitjavila","Guille Soler"],["Luis Lanuza","Edu Soler"],["Laia Casafont Corominas","Fiona Garriga Torné"],["Alexandra Biosca","Elena Altes"],["Humberto Rios","Àngel Barrera"],["Nacho Palou","Jorge Palou"],["Alex Herrera","Daniel Capdevila"]];
const STORAGE_KEY="torneig2026_state_v5";const BC=typeof BroadcastChannel!=="undefined"?new BroadcastChannel("torneig2026"):null;
const P1_GROUPS={A:["A1","A2","A3"],B:["B1","B2","B3"],C:["C1","C2","C3"],D:["D1","D2","D3"],E:["E1","E2","E3"],F:["F1","F2","F3"],G:["G1","G2","G3"],H:["H1","H2","H3"]};
const P2_GROUPS={I:["I1","I2","I3"],J:["J1","J2","J3"],K:["K1","K2","K3"],L:["L1","L2","L3"],M:["M1","M2","M3"],N:["N1","N2","N3"],O:["O1","O2","O3"],P:["P1","P2","P3"]};
const P2_SOURCES={I:[["S1","1A"],["1A","2B"],["S1","2B"]],J:[["S2","1B"],["1B","2C"],["S2","2C"]],K:[["S3","1C"],["1C","2D"],["S3","2D"]],L:[["S4","1D"],["1D","2E"],["S4","2E"]],M:[["S5","1E"],["1E","2F"],["S5","2F"]],N:[["S6","1F"],["1F","2G"],["S6","2G"]],O:[["S7","1G"],["1G","2H"],["S7","2H"]],P:[["S8","1H"],["1H","2A"],["S8","2A"]]};
const V_SOURCES={V1:["1I","2M"],V2:["1J","2N"],V3:["1K","2O"],V4:["1L","2P"],V5:["1M","2I"],V6:["1N","2J"],V7:["1O","2K"],V8:["1P","2L"]};
const Q_SOURCES={Q1:["V1","V3"],Q2:["V2","V4"],Q3:["V5","V7"],Q4:["V6","V8"]};
const TIMES={B1:"Dijous 10 · 18:00",C1:"Dijous 10 · 18:20",D1:"Dijous 10 · 18:40",B2:"Dijous 10 · 19:00",C2:"Dijous 10 · 19:20",D2:"Dijous 10 · 19:40",B3:"Dijous 10 · 20:00",C3:"Dijous 10 · 20:20",D3:"Dijous 10 · 20:40",E2:"Dijous 10 · 21:00",H1:"Divendres 11 · 09:20",F3:"Divendres 11 · 09:40",G1:"Divendres 11 · 10:00",E1:"Divendres 11 · 10:20",H2:"Divendres 11 · 10:40",F2:"Divendres 11 · 11:00",G2:"Divendres 11 · 11:20",A1:"Divendres 11 · 11:40",E3:"Divendres 11 · 12:00",H3:"Divendres 11 · 12:20",A2:"Divendres 11 · 12:40",F1:"Divendres 11 · 13:00",G3:"Divendres 11 · 13:20",A3:"Divendres 11 · 13:40",I1:"Divendres 11 · 17:00",J1:"Divendres 11 · 17:25",K1:"Divendres 11 · 17:50",I2:"Divendres 11 · 18:15",J2:"Divendres 11 · 18:40",K2:"Divendres 11 · 19:05",I3:"Divendres 11 · 19:30",J3:"Divendres 11 · 19:55",K3:"Divendres 11 · 20:20",L1:"Divendres 11 · 20:45",M1:"Divendres 11 · 21:10",N1:"Dissabte 12 · 09:00",O1:"Dissabte 12 · 09:25",P1:"Dissabte 12 · 09:50",L2:"Dissabte 12 · 10:15",M2:"Dissabte 12 · 10:40",N2:"Dissabte 12 · 11:05",O2:"Dissabte 12 · 11:30",P2:"Dissabte 12 · 11:55",L3:"Dissabte 12 · 12:20",M3:"Dissabte 12 · 12:45",N3:"Dissabte 12 · 13:10",O3:"Dissabte 12 · 13:35",P3:"Dissabte 12 · 14:00",V1:"Dissabte 12 · 16:35",V2:"Dissabte 12 · 17:00",V3:"Dissabte 12 · 17:25",V4:"Dissabte 12 · 17:50",V5:"Dissabte 12 · 18:15",V6:"Dissabte 12 · 18:40",V7:"Dissabte 12 · 19:05",V8:"Dissabte 12 · 19:30",Q1:"Dissabte 12 · 19:55",Q2:"Dissabte 12 · 20:20",Q3:"Dissabte 12 · 20:45",Q4:"Dissabte 12 · 21:10",S1:"Dissabte 12 · 21:35",S2:"Dissabte 12 · 22:00","3/4":"Dissabte 12 · 22:45",FINAL:"Dissabte 12 · 23:10"};
const ORDER=["B1","C1","D1","B2","C2","D2","B3","C3","D3","E2","H1","F3","G1","E1","H2","F2","G2","A1","E3","H3","A2","F1","G3","A3","I1","J1","K1","I2","J2","K2","I3","J3","K3","L1","M1","N1","O1","P1","L2","M2","N2","O2","P2","L3","M3","N3","O3","P3","V1","V2","V3","V4","V5","V6","V7","V8","Q1","Q2","Q3","Q4","S1","S2","3/4","FINAL"];
function stageOf(id){if(/^[A-H][1-3]$/.test(id))return`1a fase · Grup ${id[0]}`;if(/^[I-P][1-3]$/.test(id))return`2a fase · Grup ${id[0]}`;if(/^V/.test(id))return"1/8";if(/^Q/.test(id))return"1/4";if(/^S/.test(id))return"1/2";if(id==="3/4")return"3r i 4t";if(id==="FINAL")return"Final";return"Partit"}
function freshState(){const matches={};ORDER.forEach(id=>matches[id]={id,stage:stageOf(id),team1:null,team2:null,s1:0,s2:0,status:"pendent",time:TIMES[id]||"",court:"Pista 1",history:[]});return{pairs:DEFAULT_PAIRS.map(x=>[...x]),matches,activeMatch:ORDER[0],updatedAt:new Date().toISOString()}}
function loadState(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null"),s=raw||freshState();ORDER.forEach(id=>{if(!s.matches[id])s.matches[id]=freshState().matches[id];if(!s.matches[id].time)s.matches[id].time=TIMES[id]||""});return s}catch{return freshState()}}
function pairName(p){if(!p)return"—";if(Array.isArray(p))return p.filter(Boolean).join(" / ")||"—";return String(p)}function key(p){return pairName(p).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim()}function same(a,b){return !!a&&!!b&&key(a)===key(b)}function winner(m){if(!m||m.status!=="final"||!m.team1||!m.team2||m.s1===m.s2)return null;return m.s1>m.s2?m.team1:m.team2}function loser(m){if(!m||m.status!=="final"||!m.team1||!m.team2||m.s1===m.s2)return null;return m.s1>m.s2?m.team2:m.team1}
function rankGroup(s,ids){const ms=ids.map(id=>s.matches[id]).filter(Boolean);if(ms.length!==3||ms.some(m=>m.status!=="final"||!m.team1||!m.team2||m.s1===m.s2))return[];const map=new Map();const row=p=>{const k=key(p);if(!map.has(k))map.set(k,{p,w:0,pf:0,pa:0});return map.get(k)};ms.forEach(m=>{const a=row(m.team1),b=row(m.team2);a.pf+=+m.s1||0;a.pa+=+m.s2||0;b.pf+=+m.s2||0;b.pa+=+m.s1||0;if(m.s1>m.s2)a.w++;else b.w++});return[...map.values()].sort((a,b)=>b.w-a.w||(b.pf-b.pa)-(a.pf-a.pa)||b.pf-a.pf||pairName(a.p).localeCompare(pairName(b.p))).map(x=>x.p)}
function source(s,src){let m;if((m=/^S([1-8])$/.exec(src)))return s.pairs[+m[1]-1]||null;if((m=/^([12])([A-H])$/.exec(src))){const r=rankGroup(s,P1_GROUPS[m[2]]);return r[+m[1]-1]||null}if((m=/^([12])([I-P])$/.exec(src))){const r=rankGroup(s,P2_GROUPS[m[2]]);return r[+m[1]-1]||null}if((m=/^(?:Guanyador )?(V\d|Q\d|S\d)$/.exec(src)))return winner(s.matches[m[1]]);if((m=/^Perdedor (S\d)$/.exec(src)))return loser(s.matches[m[1]]);return null}
function havePlayed(s,a,b){if(!a||!b)return false;return ORDER.some(id=>{const m=s.matches[id];return m&&m.status==="final"&&((same(m.team1,a)&&same(m.team2,b))||(same(m.team1,b)&&same(m.team2,a)))})}
function setTeams(m,a,b){if(!m)return;m.team1=a||null;m.team2=b||null}
function propagate(s){Object.entries(P2_GROUPS).forEach(([g,ids])=>ids.forEach((id,i)=>{const z=P2_SOURCES[g][i];setTeams(s.matches[id],source(s,z[0]),source(s,z[1]))}));Object.entries(V_SOURCES).forEach(([id,z])=>setTeams(s.matches[id],source(s,z[0]),source(s,z[1])));Object.entries(Q_SOURCES).forEach(([id,z])=>setTeams(s.matches[id],winner(s.matches[z[0]]),winner(s.matches[z[1]])));const qw=["Q1","Q2","Q3","Q4"].map(id=>winner(s.matches[id]));if(qw.every(Boolean)){const opts=[[[0,1],[2,3]],[[0,2],[1,3]],[[0,3],[1,2]]];opts.sort((a,b)=>a.flatMap(x=>[havePlayed(s,qw[x[0]],qw[x[1]])]).filter(Boolean).length-b.flatMap(x=>[havePlayed(s,qw[x[0]],qw[x[1]])]).filter(Boolean).length);const p=opts[0];setTeams(s.matches.S1,qw[p[0][0]],qw[p[0][1]]);setTeams(s.matches.S2,qw[p[1][0]],qw[p[1][1]])}else{setTeams(s.matches.S1,null,null);setTeams(s.matches.S2,null,null)}setTeams(s.matches.FINAL,winner(s.matches.S1),winner(s.matches.S2));setTeams(s.matches["3/4"],loser(s.matches.S1),loser(s.matches.S2));return s}
async function logScoreChanges(before,after){if(!window.SupaSync?.req)return;try{if(!(await window.SupaSync.isStaff()))return;for(const id of ORDER){const a=before?.matches?.[id],b=after?.matches?.[id];if(!b)continue;const scoreChanged=!a||Number(a.s1||0)!==Number(b.s1||0)||Number(a.s2||0)!==Number(b.s2||0);const started=b.status==='en joc'&&a?.status!=='en joc'&&a?.status!=='final';if(!scoreChanged&&!started)continue;await window.SupaSync.req('/rest/v1/match_score_history',{method:'POST',body:{tournament_id:'2026',match_id:id,score1:Number(b.s1||0),score2:Number(b.s2||0),event_type:started&&!scoreChanged?'start':'score'}})}}catch(e){console.warn('Score history',e)}}
function saveState(s){let before=null;try{before=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{}propagate(s);s.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s));if(BC)BC.postMessage({type:'state'});if(window.SupaSync)window.SupaSync.pushTournamentState(s).catch(e=>console.warn('Supabase sync',e));logScoreChanges(before,s)}function finalizeMatch(s,id){const m=s.matches[id];if(!m)return false;if(!m.team1||!m.team2){alert("Les dues parelles han d'estar definides.");return false}if(m.s1===m.s2){alert("El partit no pot acabar empatat.");return false}m.status='final';propagate(s);saveState(s);return true}function score(s,id,side,delta){const m=s.matches[id];if(!m||m.status==='final')return;const k=side===1?'s1':'s2';m[k]=Math.max(0,(m[k]||0)+delta);m.status='en joc';saveState(s)}function allIds(){return[...ORDER]}function nextPending(s,current){const i=Math.max(0,ORDER.indexOf(current));for(let k=i+1;k<ORDER.length;k++){const m=s.matches[ORDER[k]];if(m&&m.status!=='final'&&m.team1&&m.team2)return ORDER[k]}return ORDER.find(id=>{const m=s.matches[id];return m&&m.status!=='final'&&m.team1&&m.team2})||current}function escapeHtml(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]))}window.Torneig={loadState,saveState,freshState,propagate,finalizeMatch,score,pairName,allIds,nextPending,escapeHtml,stageOf,winner,loser,DEFAULT_TIMES:TIMES,STORAGE_KEY,BC,FINAL_ID:'FINAL',rankGroup};

(function(){
  function sourceText(id){
    if(P2_SOURCES[id?.[0]]){const z=P2_SOURCES[id[0]][Number(id[1])-1];return z?z.map(labelSource):[]}
    if(V_SOURCES[id])return V_SOURCES[id].map(labelSource);
    if(Q_SOURCES[id])return Q_SOURCES[id].map(x=>'Guanyador '+x);
    if(id==='S1'||id==='S2')return ['Guanyador de quarts','Guanyador de quarts'];
    if(id==='3/4')return ['Perdedor S1','Perdedor S2'];
    if(id==='FINAL')return ['Guanyador S1','Guanyador S2'];
    return [];
  }
  function labelSource(s){let m;if((m=/^S(\d+)$/.exec(s)))return 'Cap de sèrie #'+m[1];if((m=/^([12])([A-P])$/.exec(s)))return (m[1]==='1'?'1r':'2n')+' Grup '+m[2];return s}
  function installOfficialSchedule(){
    if(location.pathname.replace(/\.html$/,'')!=='/horaris')return;
    const note=document.querySelector('.schedule-note');if(note)note.innerHTML='<strong>✓ Sorteig oficial.</strong> Els grups i horaris ja són definitius. A partir de la 2a fase, els encreuaments es resolen segons classificació evitant repetir rival sempre que hi hagi una alternativa.';
    window.matchLabel=function(m){const status=m.status==='final'?`Finalitzat · ${m.s1}–${m.s2}`:m.status==='en joc'?'Partit en joc':'Pendent';const src=sourceText(m.id);const a=m.team1?Torneig.pairName(m.team1):(src[0]||'Per definir');const b=m.team2?Torneig.pairName(m.team2):(src[1]||'Per definir');return `<div class="schedule-teams">${Torneig.escapeHtml(a)} <span style="color:#829089;font-weight:700">vs</span> ${Torneig.escapeHtml(b)}<small>${status}</small></div>`};
    const refresh=async()=>{try{if(window.SupaSync?.loadTournament)await window.SupaSync.loadTournament()}catch{}try{if(typeof window.render==='function')window.render()}catch{}};
    setTimeout(refresh,250);setTimeout(refresh,1100);
    const mo=new MutationObserver(()=>{const n=document.querySelector('.schedule-note');if(n&&n.textContent.includes('Sorteig pendent'))n.innerHTML='<strong>✓ Sorteig oficial.</strong> Els grups i horaris ja són definitius.'});mo.observe(document.body,{childList:true,subtree:true});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(installOfficialSchedule,0));else setTimeout(installOfficialSchedule,0);
})();
