const DEFAULT_PAIRS=[
  ["Adri Salaverría","María Salaverría"],["Albert Cabezas","Ramon Romero"],["Mauro Lenhardi","Roger Juanola"],["Julia Serrano","Juan Sobreroca"],
  ["Alvaro Palou","Pepe Palou"],["Lluís Aymami","Diego Salvo"],["Marc Muntané","Alex Sanchez"],["Arnau Costa","Otger Costa"],
  ["Maurici Monguet","Marius Alcala"],["Marc Balcells","Manel Villegas"],["Lluís Cabezas","Xavi Palou Pare"],["Sergi Ripollés","Ferran Cabezas"],
  ["Edu Llop","David Llop"],["Jordi Civit","Laura Soler Pericas"],["Toni Civit","Jordi Balcells Senior"],["Pol Gaynes","Gerard Civit"],
  ["Claudia Balcells","Jemi Recasens"],["Sara Vidal","Blanca Josep"],["Ian Dameson","Eloi de la Torre"],["Paula Quilez","Marc Cid"],
  ["Carlota Domínguez","Joel Socias"],["Pau Tetas","Ángel Sáenz"],["Guillem Tost","Joan Valette"],["Albert Civit","Ramon Maria Nadal"],
  ["Pol Mitjavila","Martí Coma"],["Claudia Mitjavila","Guille Soler"],["Luis Lanuza","Edu Soler"],["Laia Casafont Corominas","Fiona Garriga Torné"],
  ["Alexandra Biosca","Elena Altes"],["Parella 32","Pendent"],["Nacho Palou","Jorge Palou"],["Alex Herrera","Daniel Capdevila"]
];
const FIRST_GROUPS={A:[9,17,18],B:[10,19,20],C:[11,21,22],D:[12,23,24],E:[13,25,26],F:[14,27,28],G:[15,29,30],H:[16,31,32]};
const SECOND_GROUPS={I:[1,"1A","2B"],J:[2,"1B","2C"],K:[3,"1C","2D"],L:[4,"1D","2E"],M:[5,"1E","2F"],N:[6,"1F","2G"],O:[7,"1G","2H"],P:[8,"1H","2A"]};
const QUARTER_GROUPS=[["I","M"],["J","N"],["K","O"],["L","P"]],GROUP_PAIRINGS=[[0,1],[1,2],[0,2]];
const FIRST_IDS=Object.keys(FIRST_GROUPS).flatMap(g=>[1,2,3].map(n=>`${g}${n}`)),SECOND_IDS=Object.keys(SECOND_GROUPS).flatMap(g=>[1,2,3].map(n=>`${g}${n}`));
const Q_IDS=["Q1","Q2","Q3","Q4"],S_IDS=["S1","S2"],FINAL_ID="FINAL",F_IDS=["3/4",FINAL_ID];
const STORAGE_KEY="torneig2026_state_groups_v1",BC=typeof BroadcastChannel!=="undefined"?new BroadcastChannel("torneig2026"):null;
const DEFAULT_TIMES={
  B1:"Dijous 10 · 17:00",C1:"Dijous 10 · 17:20",D1:"Dijous 10 · 17:40",E1:"Dijous 10 · 18:00",H1:"Dijous 10 · 18:20",G1:"Dijous 10 · 18:40",B2:"Dijous 10 · 19:00",C2:"Dijous 10 · 19:20",D2:"Dijous 10 · 19:40",E2:"Dijous 10 · 20:00",H2:"Dijous 10 · 20:20",B3:"Dijous 10 · 20:40",G3:"Dijous 10 · 21:00",
  C3:"Divendres 11 · 09:40",D3:"Divendres 11 · 10:00",E3:"Divendres 11 · 10:20",H3:"Divendres 11 · 10:40",G2:"Divendres 11 · 11:00",F1:"Divendres 11 · 11:20",A1:"Divendres 11 · 11:40",F2:"Divendres 11 · 12:00",A2:"Divendres 11 · 12:20",F3:"Divendres 11 · 12:40",A3:"Divendres 11 · 13:00",
  I1:"Divendres 11 · 13:40",J1:"Divendres 11 · 14:00",K1:"Divendres 11 · 17:00",L1:"Divendres 11 · 17:20",M1:"Divendres 11 · 17:40",N1:"Divendres 11 · 18:00",O1:"Divendres 11 · 18:20",P1:"Divendres 11 · 18:40",I2:"Divendres 11 · 19:00",J2:"Divendres 11 · 19:20",K2:"Divendres 11 · 19:40",L2:"Divendres 11 · 20:00",M2:"Divendres 11 · 20:20",N2:"Divendres 11 · 20:40",O2:"Divendres 11 · 21:00",P2:"Divendres 11 · 21:20",
  I3:"Dissabte 12 · 09:30",J3:"Dissabte 12 · 09:50",K3:"Dissabte 12 · 10:10",L3:"Dissabte 12 · 10:30",M3:"Dissabte 12 · 10:50",N3:"Dissabte 12 · 11:10",O3:"Dissabte 12 · 11:30",P3:"Dissabte 12 · 11:50",Q1:"Dissabte 12 · 16:30",Q2:"Dissabte 12 · 17:00",Q3:"Dissabte 12 · 17:30",Q4:"Dissabte 12 · 18:00",S1:"Dissabte 12 · 19:00",S2:"Dissabte 12 · 19:30","3/4":"Dissabte 12 · 20:30",FINAL:"Dissabte 12 · 21:00"
};
const AVAILABILITY=[
  {pair:["Toni Civit","Jordi Balcells Senior"],text:"Dijous de 19.00 a 21.00"},{pair:["Luis Lanuza","Edu Soler"],text:"No pot jugar dijous"},
  {pair:["Claudia Balcells","Jemi Recasens"],text:"No pot jugar dijous"},{pair:["Maurici Monguet","Marius Alcala"],text:"No pot jugar dijous; divendres a partir de les 11.30"},
  {pair:["Mauro Lenhardi","Roger Juanola"],text:"Dijous només a partir de les 20.00"}
];
function validPair(p){return Array.isArray(p)&&p.filter(Boolean).length===2}
function pairName(p){return validPair(p)?p.join(" / "):"Per definir"}
function pairKey(p){return validPair(p)?p.map(x=>String(x).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim()).sort().join("|"):""}
function stageOf(id){if(FIRST_IDS.includes(id))return`1a fase · Grup ${id[0]}`;if(SECOND_IDS.includes(id))return`2a fase · Grup ${id[0]}`;if(Q_IDS.includes(id))return"1/4";if(S_IDS.includes(id))return"1/2";if(id===FINAL_ID)return"Final";if(id==="3/4")return"3r i 4t";return""}
function makeMatch(id,team1=null,team2=null){return{id,stage:stageOf(id),team1:validPair(team1)?team1:null,team2:validPair(team2)?team2:null,s1:0,s2:0,status:"pendent",time:DEFAULT_TIMES[id]||"",court:"Pista 1",history:[]}}
function freshState(){const s={pairs:DEFAULT_PAIRS.map(p=>[...p]),matches:{},activeMatch:FIRST_IDS[0],updatedAt:new Date().toISOString()};Object.entries(FIRST_GROUPS).forEach(([g,seeds])=>GROUP_PAIRINGS.forEach(([a,b],i)=>s.matches[`${g}${i+1}`]=makeMatch(`${g}${i+1}`,s.pairs[seeds[a]-1],s.pairs[seeds[b]-1])));[...SECOND_IDS,...Q_IDS,...S_IDS,...F_IDS].forEach(id=>s.matches[id]=makeMatch(id));propagate(s);return s}
function normalizeState(s){if(!s||!s.matches||!FIRST_IDS.every(id=>s.matches[id]))return freshState();s.pairs=s.pairs||DEFAULT_PAIRS.map(p=>[...p]);allIds().forEach(id=>{if(!s.matches[id])s.matches[id]=makeMatch(id);s.matches[id].stage=stageOf(id);s.matches[id].time=s.matches[id].time||DEFAULT_TIMES[id]||"";s.matches[id].court=s.matches[id].court||"Pista 1";s.matches[id].history=Array.isArray(s.matches[id].history)?s.matches[id].history:[]});propagate(s);return s}
function loadState(){try{return normalizeState(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{return freshState()}}
function winner(m){if(!m||m.status!=="final"||m.s1===m.s2)return null;return m.s1>m.s2?m.team1:m.team2}
function loser(m){if(!m||m.status!=="final"||m.s1===m.s2)return null;return m.s1>m.s2?m.team2:m.team1}
function groupTeams(s,phase,group){const spec=phase===1?FIRST_GROUPS[group]:SECOND_GROUPS[group];return(spec||[]).map(x=>typeof x==="number"?(validPair(s.pairs[x-1])?s.pairs[x-1]:null):qualifiedPair(s,x))}
function groupMatches(s,phase,group){return[1,2,3].map(n=>s.matches[`${group}${n}`]).filter(Boolean)}
function standingsTieCount(s,phase,group,wins){const keys=groupTeams(s,phase,group).filter(validPair).map(pairKey),tot=new Map(keys.map(k=>[k,0]));groupMatches(s,phase,group).forEach(m=>{if(m.status==="final"&&m.s1!==m.s2){const k=pairKey(winner(m));if(tot.has(k))tot.set(k,tot.get(k)+1)}});return[...tot.values()].filter(v=>v===wins).length}
function headToHead(s,phase,group,a,b){if(standingsTieCount(s,phase,group,a.pg)!==2)return 0;const m=groupMatches(s,phase,group).find(x=>x.status==="final"&&[pairKey(x.team1),pairKey(x.team2)].includes(a.key)&&[pairKey(x.team1),pairKey(x.team2)].includes(b.key));if(!m||m.s1===m.s2)return 0;return pairKey(winner(m))===a.key?-1:1}
function standings(s,phase,group){const teams=groupTeams(s,phase,group).filter(validPair),rows=teams.map((team,index)=>({team,index,key:pairKey(team),pj:0,pg:0,pp:0,pf:0,pc:0,dif:0})),by=new Map(rows.map(r=>[r.key,r]));groupMatches(s,phase,group).forEach(m=>{if(m.status!=="final"||!validPair(m.team1)||!validPair(m.team2)||m.s1===m.s2)return;const a=by.get(pairKey(m.team1)),b=by.get(pairKey(m.team2));if(!a||!b)return;a.pj++;b.pj++;a.pf+=Number(m.s1)||0;a.pc+=Number(m.s2)||0;b.pf+=Number(m.s2)||0;b.pc+=Number(m.s1)||0;if(m.s1>m.s2){a.pg++;b.pp++}else{b.pg++;a.pp++}});rows.forEach(r=>r.dif=r.pf-r.pc);rows.sort((a,b)=>b.pg-a.pg||headToHead(s,phase,group,a,b)||b.dif-a.dif||b.pf-a.pf||a.index-b.index);return rows}
function groupComplete(s,phase,group){return groupMatches(s,phase,group).every(m=>m.status==="final"&&validPair(m.team1)&&validPair(m.team2)&&m.s1!==m.s2)}
function qualifiedPair(s,source){const m=String(source||"").match(/^([12])([A-H])$/);if(!m||!groupComplete(s,1,m[2]))return null;return standings(s,1,m[2])[Number(m[1])-1]?.team||null}
function secondWinner(s,group){return groupComplete(s,2,group)?standings(s,2,group)[0]?.team||null:null}
function setTeams(m,a,b){if(!m)return;const changed=pairKey(m.team1)!==pairKey(a)||pairKey(m.team2)!==pairKey(b);m.team1=validPair(a)?a:null;m.team2=validPair(b)?b:null;if(changed&&m.status!=="pendent"){m.s1=0;m.s2=0;m.history=[];m.status="pendent"}}
function meetings(s,a,b){if(!validPair(a)||!validPair(b))return 0;const ka=pairKey(a),kb=pairKey(b);return allIds().filter(id=>!S_IDS.includes(id)&&id!=="3/4"&&id!==FINAL_ID).map(id=>s.matches[id]).filter(m=>m?.status==="final"&&[pairKey(m.team1),pairKey(m.team2)].includes(ka)&&[pairKey(m.team1),pairKey(m.team2)].includes(kb)).length}
function semifinalPairing(s){const q=Q_IDS.map(id=>winner(s.matches[id]));if(q.some(x=>!validPair(x)))return[[null,null],[null,null]];const options=[[[0,1],[2,3]],[[0,2],[1,3]],[[0,3],[1,2]]];options.sort((x,y)=>x.reduce((n,p)=>n+meetings(s,q[p[0]],q[p[1]]),0)-y.reduce((n,p)=>n+meetings(s,q[p[0]],q[p[1]]),0));return options[0].map(([a,b])=>[q[a],q[b]])}
function propagate(s){Object.entries(FIRST_GROUPS).forEach(([g,seeds])=>GROUP_PAIRINGS.forEach(([a,b],i)=>setTeams(s.matches[`${g}${i+1}`],s.pairs[seeds[a]-1],s.pairs[seeds[b]-1])));Object.keys(SECOND_GROUPS).forEach(g=>{const teams=groupTeams(s,2,g);GROUP_PAIRINGS.forEach(([a,b],i)=>setTeams(s.matches[`${g}${i+1}`],teams[a],teams[b]))});QUARTER_GROUPS.forEach((g,i)=>setTeams(s.matches[Q_IDS[i]],secondWinner(s,g[0]),secondWinner(s,g[1])));const semis=semifinalPairing(s);S_IDS.forEach((id,i)=>setTeams(s.matches[id],semis[i][0],semis[i][1]));setTeams(s.matches.FINAL,winner(s.matches.S1),winner(s.matches.S2));setTeams(s.matches["3/4"],loser(s.matches.S1),loser(s.matches.S2))}
async function logScoreChanges(before,after){if(!window.SupaSync?.req)return;try{if(!(await window.SupaSync.isStaff()))return;for(const id of allIds()){const a=before?.matches?.[id],b=after?.matches?.[id];if(!b)continue;const scoreChanged=!a||Number(a.s1||0)!==Number(b.s1||0)||Number(a.s2||0)!==Number(b.s2||0),started=b.status==="en joc"&&a?.status!=="en joc"&&a?.status!=="final";if(!scoreChanged&&!started)continue;await window.SupaSync.req("/rest/v1/match_score_history",{method:"POST",body:{tournament_id:"2026",match_id:id,score1:Number(b.s1||0),score2:Number(b.s2||0),event_type:started&&!scoreChanged?"start":"score"}})}}catch(e){console.warn("Score history",e)}}
function saveState(s){let before=null;try{before=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")}catch{}propagate(s);s.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s));BC?.postMessage({type:"state"});window.SupaSync?.pushTournamentState(s).catch(e=>console.warn("Supabase sync",e));logScoreChanges(before,s)}
function finalizeMatch(s,id){const m=s.matches[id];if(!m||!validPair(m.team1)||!validPair(m.team2)){alert("Les dues parelles han d'estar definides.");return false}if(m.s1===m.s2){alert("El partit no pot acabar empatat.");return false}m.status="final";propagate(s);saveState(s);return true}
function score(s,id,side,delta){const m=s.matches[id];if(!m||m.status==="final")return;const key=side===1?"s1":"s2";m[key]=Math.max(0,(m[key]||0)+delta);m.status="en joc";saveState(s)}
function allIds(){return[...FIRST_IDS,...SECOND_IDS,...Q_IDS,...S_IDS,...F_IDS]}
function nextPending(s,current){const ids=allIds(),i=Math.max(0,ids.indexOf(current));for(let k=i+1;k<ids.length;k++)if(s.matches[ids[k]].status!=="final"&&validPair(s.matches[ids[k]].team1)&&validPair(s.matches[ids[k]].team2))return ids[k];return ids.find(id=>s.matches[id].status!=="final"&&validPair(s.matches[id].team1)&&validPair(s.matches[id].team2))||current}
function escapeHtml(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
window.Torneig={loadState,saveState,freshState,propagate,finalizeMatch,score,pairName,pairKey,validPair,allIds,nextPending,escapeHtml,stageOf,winner,loser,standings,groupTeams,groupComplete,qualifiedPair,secondWinner,FIRST_GROUPS,SECOND_GROUPS,QUARTER_GROUPS,FIRST_IDS,SECOND_IDS,Q_IDS,S_IDS,DEFAULT_TIMES,DEFAULT_PAIRS,AVAILABILITY,STORAGE_KEY,BC,FINAL_ID};
