(()=>{
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
  const firstTwo=s=>norm(s).split(' ').filter(Boolean).slice(0,2).join(' ');
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
  let names=[],loaded=false,loading=null;
  function injectStyle(){if(document.getElementById('db-name-picker-style'))return;const st=document.createElement('style');st.id='db-name-picker-style';st.textContent=`.db-name-picker-wrap{position:relative;min-width:0}.db-name-picker-menu{position:absolute;z-index:99999;left:0;top:calc(100% + 8px);width:min(520px,max(100%,360px));max-width:min(520px,calc(100vw - 48px));max-height:360px;overflow-y:auto;overflow-x:hidden;background:#fff;border:1px solid #d7e2dc;border-radius:16px;box-shadow:0 22px 55px rgba(7,48,34,.22);display:none;padding:6px}.db-name-picker-menu.open{display:block}.db-name-picker-option{display:flex!important;align-items:center;justify-content:space-between;gap:16px;width:100%;border:0!important;border-radius:10px!important;background:#fff!important;text-align:left!important;padding:11px 12px!important;min-height:46px!important;cursor:pointer;font-family:inherit!important;color:#17332a!important}.db-name-picker-option:hover,.db-name-picker-option.active{background:#eef7f2!important}.db-name-picker-option strong{font-size:14px!important;color:#123d2e}.db-name-picker-hint{font-size:10px!important;color:#718078;white-space:nowrap}@media(max-width:700px){.db-name-picker-menu{left:0;right:0;width:100%;max-width:100%;max-height:300px}.db-name-picker-option{display:block!important}.db-name-picker-hint{display:block;margin-top:3px}}`;document.head.appendChild(st)}
  async function loadNames(){if(loaded)return names;if(loading)return loading;loading=(async()=>{if(!window.SupaSync?.req)return[];const safe=(path,opt)=>SupaSync.req(path,opt).catch(()=>[]);const[players,members,regs,meals]=await Promise.all([safe('/rest/v1/players?select=full_name'),safe('/rest/v1/rpc/public_member_registry',{method:'POST',body:{}}),safe('/rest/v1/rpc/public_registration_summary',{method:'POST',body:{}}),safe('/rest/v1/rpc/public_lunch_reservations',{method:'POST',body:{}})]);const all=[];(players||[]).forEach(x=>x.full_name&&all.push(x.full_name));(members||[]).forEach(x=>x.full_name&&all.push(x.full_name));(regs||[]).forEach(x=>{x.player1_name&&all.push(x.player1_name);x.player2_name&&all.push(x.player2_name)});(meals||[]).forEach(x=>x.full_name&&all.push(x.full_name));const uniq=new Map();all.forEach(v=>{v=String(v||'').trim();if(v)uniq.set(norm(v),v)});names=[...uniq.values()].sort((a,b)=>a.localeCompare(b,'ca',{sensitivity:'base'}));loaded=true;return names})();return loading}
  function descriptor(input){const label=input.closest('.field')?.querySelector('label')?.textContent||input.getAttribute('aria-label')||'';return norm([input.id,input.placeholder,label].join(' '))}
  function shouldAttach(input){if(input.dataset.dbNamePicker==='off'||input.disabled||input.readOnly)return false;const d=descriptor(input),isSearch=input.type==='search'||/search|buscar/.test(d);if(!isSearch)return false;if(/producte|talla|partit|fase|horari|hora|pista|missatge|titol/.test(d))return false;return /nom|cognom|jugador|parella|soci|persona|assistent/.test(d)||['q','pairSearch','paySearch','barSearch'].includes(input.id)}
  function attach(input){if(input.dataset.dbNamePickerBound==='1')return;input.dataset.dbNamePickerBound='1';input.autocomplete='off';injectStyle();const parent=input.parentElement;parent.classList.add('db-name-picker-wrap');const menu=document.createElement('div');menu.className='db-name-picker-menu';parent.appendChild(menu);let selected='',choosing=false,current=[];const choose=v=>{if(!v)return;choosing=true;selected=v;input.value=v;menu.classList.remove('open');input.dispatchEvent(new Event('change',{bubbles:true}));input.dispatchEvent(new CustomEvent('namepicker:selected',{bubbles:true,detail:{name:v}}));setTimeout(()=>choosing=false,0)};const render=async()=>{if(choosing)return;const list=await loadNames(),q=norm(input.value);current=(q?list.filter(n=>norm(n).includes(q)||firstTwo(n).includes(firstTwo(q))):list).slice(0,18);menu.innerHTML=current.length?current.map((n,i)=>`<button type="button" class="db-name-picker-option" data-i="${i}"><strong>${esc(n)}</strong><span class="db-name-picker-hint">Seleccionar</span></button>`).join(''):'<div class="db-name-picker-option"><strong>Cap coincidència</strong></div>';menu.classList.add('open');menu.querySelectorAll('[data-i]').forEach(b=>b.onclick=e=>{e.preventDefault();choose(current[Number(b.dataset.i)])})};input.addEventListener('focus',render);input.addEventListener('input',()=>{if(!choosing)render()});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&current.length===1){e.preventDefault();choose(current[0])}if(e.key==='Escape')menu.classList.remove('open')})}
  function scan(){document.querySelectorAll('input').forEach(i=>{if(shouldAttach(i))attach(i)})}
  document.addEventListener('pointerdown',e=>{document.querySelectorAll('.db-name-picker-menu.open').forEach(menu=>{if(!menu.parentElement?.contains(e.target))menu.classList.remove('open')})},true);
  window.DBNamePicker={scan,reload:()=>{loaded=false;loading=null;return loadNames()}};scan();new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});

  // El meu torneig: guarda sempre el jugador realment obert, també a mòbil.
  if(location.pathname.replace(/\.html$/,'')==='/el-meu-torneig'){
    const persist=()=>{const result=document.getElementById('result');if(!result)return;const eyebrow=[...result.querySelectorAll('.eyebrow')].find(x=>/jugador localitzat/i.test(x.textContent||''));const h2=eyebrow?.parentElement?.querySelector('h2')||result.querySelector('.identity h2');const n=String(h2?.textContent||'').trim();if(n){if(window.MyIdentity?.set)MyIdentity.set(n);else localStorage.setItem('frontenis_my_name_2026',n)}};
    const hook=()=>{const result=document.getElementById('result');if(!result)return false;new MutationObserver(()=>setTimeout(persist,0)).observe(result,{childList:true,subtree:true});persist();return true};
    if(!hook()){let tries=0;const t=setInterval(()=>{if(hook()||++tries>40)clearInterval(t)},100)}
    document.addEventListener('click',e=>{if(e.target.closest('#searchBtn'))setTimeout(persist,500)},true);
  }
})();