(()=>{
const URL='https://mojwomfkgpvpwviqnptl.supabase.co';
const KEY='sb_publishable_UtAmoVy3jwRJe1ehoGJI_g_oBsh5jvl';
const SESSION_KEY='torneig2026_supabase_session';const PORTAL_KEY='torneig2026_portal_data';const STATE_KEY='torneig2026_state_v5';
let client=null,pairMap=new Map(),lastMatchSnapshot={},syncChain=Promise.resolve(),realtimeStarted=false;
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim(),pairKey=p=>Array.isArray(p)?norm(p.filter(Boolean).join('|')):norm(p);
function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}function token(){return session()?.access_token||KEY}
async function refreshSession(){const s=session();if(!s?.refresh_token)return null;try{const r=await fetch(URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});const d=await r.json();if(!r.ok||!d?.access_token)throw 0;localStorage.setItem(SESSION_KEY,JSON.stringify(d));return d}catch{localStorage.removeItem(SESSION_KEY);return null}}
async function req(path,opt={}){const go=a=>fetch(URL+path,{method:opt.method||'GET',headers:{apikey:KEY,Authorization:`Bearer ${a}`,'Content-Type':'application/json',Prefer:opt.prefer||'return=representation',...(opt.headers||{})},body:opt.body===undefined?undefined:JSON.stringify(opt.body)});let r=await go(token());if(r.status===401&&session()){const f=await refreshSession();r=await go(f?.access_token||KEY)}if(!r.ok)throw new Error(await r.text()||`${r.status}`);if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
async function signIn(email,password){const r=await fetch(URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})}),d=await r.json();if(!r.ok)throw new Error(d.msg||d.error_description||'No s’ha pogut iniciar sessió');localStorage.setItem(SESSION_KEY,JSON.stringify(d));return d}function signOut(){localStorage.removeItem(SESSION_KEY)}async function isStaff(){try{return !!(await req('/rest/v1/rpc/is_staff',{method:'POST',body:{}}))}catch{return false}}async function isAdmin(){try{return !!(await req('/rest/v1/rpc/is_admin',{method:'POST',body:{}}))}catch{return false}}
function localPortal(){try{return JSON.parse(localStorage.getItem(PORTAL_KEY)||'{}')}catch{return {}}}function saveLocalPortal(s){localStorage.setItem(PORTAL_KEY,JSON.stringify(s))}
async function hydratePortal(){const p=localPortal();p.lunches=p.lunches||{};p.notices=p.notices||[];p.tournamentRegistrations=p.tournamentRegistrations||[];p.merchOrders=p.merchOrders||[];p.payments=p.payments||[];try{const cfg=(await req('/rest/v1/tournament_config?id=eq.2026&select=*'))?.[0];if(cfg)p.config={name:cfg.name,dates:cfg.dates,maxPairs:cfg.max_pairs,normalPrice:Number(cfg.normal_price),memberPrice:Number(cfg.member_price),mealPrice:Number(cfg.meal_price),bizum:cfg.bizum_instructions||'',phone:cfg.contact_phone||'',registrationOpen:cfg.registration_open,lunchOpen:cfg.lunch_open,merchOpen:cfg.merch_open,mvpOpen:cfg.mvp_open}}catch{}try{const ls=await req('/rest/v1/lunch_events?select=id,title,price,is_open'),rs=await req('/rest/v1/lunch_reservations?select=id,lunch_id,full_name,bizum_name,payment_status');const by={};(ls||[]).forEach(x=>{by[x.id]=x.title;p.lunches[x.title]=[]});(rs||[]).forEach(x=>{const t=by[x.lunch_id];if(t)p.lunches[t].push({id:x.id,name:x.full_name,bizumName:x.bizum_name,status:x.payment_status==='verified'?'verificat':x.payment_status==='bizum_sent'?'bizum_enviat':'pendent'})})}catch{}saveLocalPortal(p);return p}
async function createRegistration(r){return req('/rest/v1/tournament_registrations',{method:'POST',body:{player1_name:r.p1,player2_name:r.p2,player1_type:r.member1?'member':'normal',player2_type:r.member2?'member':'normal',amount:r.amount,bizum_name:r.bizumName||null,payment_status:r.status==='bizum_enviat'?'bizum_sent':'pending',status:'pending'}})}
async function reserveLunch(meal,names,bizumName,sent){const e=await req(`/rest/v1/lunch_events?title=eq.${encodeURIComponent(meal)}&select=id`);if(!e?.length)throw new Error('Àpat no configurat');const g=crypto.randomUUID();return req('/rest/v1/lunch_reservations',{method:'POST',body:names.map(n=>({lunch_id:e[0].id,full_name:n,reservation_group:g,bizum_name:bizumName||null,payment_status:sent?'bizum_sent':'pending'}))})}
async function verifyPayment(p){if(!p?.dbId)return;const table=p.dbType==='registration'?'tournament_registrations':p.dbType==='lunch'?'lunch_reservations':'merch_orders';return req(`/rest/v1/${table}?id=eq.${p.dbId}`,{method:'PATCH',body:{payment_status:'verified'}})}
async function loadTournament(){if(!window.Torneig)return null;const players=await req('/rest/v1/players?select=id,full_name'),pairs=await req('/rest/v1/pairs?tournament_id=eq.2026&order=seed.asc&select=id,seed,player1_id,player2_id,color'),matches=await req('/rest/v1/matches?tournament_id=eq.2026&select=*');if(!pairs?.length||!matches?.length)return null;const names=new Map(players.map(x=>[x.id,x.full_name])),byId=new Map(),s=Torneig.freshState();pairMap=new Map();pairs.forEach(x=>{const p=[names.get(x.player1_id)||'',names.get(x.player2_id)||''];byId.set(x.id,p);pairMap.set(pairKey(p),x.id);s.pairs[(x.seed||1)-1]=p});matches.forEach(x=>{if(!s.matches[x.id])s.matches[x.id]={id:x.id,stage:x.stage||Torneig.stageOf(x.id),team1:null,team2:null,s1:0,s2:0,status:'pendent',time:x.scheduled_at||'',court:x.court||'Pista 1',history:[]};const m=s.matches[x.id];m.stage=x.stage||m.stage;m.team1=x.team1_id?byId.get(x.team1_id)||null:null;m.team2=x.team2_id?byId.get(x.team2_id)||null:null;m.s1=x.score1||0;m.s2=x.score2||0;m.history=Array.isArray(x.score_history)?x.score_history:[];m.status=x.status==='final'?'final':x.status==='live'?'en joc':'pendent';m.time=x.scheduled_at||m.time;m.court=x.court||'Pista 1';m.team1Source=x.team1_source||null;m.team2Source=x.team2_source||null;lastMatchSnapshot[x.id]=JSON.stringify([x.team1_id,x.team2_id,x.score1,x.score2,x.status,x.scheduled_at,x.court,x.score_history||[]])});Torneig.propagate(s);localStorage.setItem(STATE_KEY,JSON.stringify(s));return s}
async function ensurePairMap(){if(pairMap.size)return;const ps=await req('/rest/v1/players?select=id,full_name'),nm=new Map(ps.map(x=>[x.id,x.full_name])),prs=await req('/rest/v1/pairs?tournament_id=eq.2026&select=id,player1_id,player2_id');prs.forEach(x=>pairMap.set(pairKey([nm.get(x.player1_id)||'',nm.get(x.player2_id)||'']),x.id))}
async function pushTournamentStateNow(s){if(!(await isStaff()))return;await ensurePairMap();for(const id of Object.keys(s.matches||{})){const m=s.matches[id],row={team1_id:m.team1?pairMap.get(pairKey(m.team1))||null:null,team2_id:m.team2?pairMap.get(pairKey(m.team2))||null:null,score1:m.s1||0,score2:m.s2||0,score_history:Array.isArray(m.history)?m.history:[],status:m.status==='final'?'final':m.status==='en joc'?'live':'pending',scheduled_at:m.time||null,court:m.court||'Pista 1',updated_at:new Date().toISOString()},fp=JSON.stringify([row.team1_id,row.team2_id,row.score1,row.score2,row.status,row.scheduled_at,row.court,row.score_history]);if(lastMatchSnapshot[id]===fp)continue;await req(`/rest/v1/matches?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:row});lastMatchSnapshot[id]=fp}}
function pushTournamentState(s){const snap=JSON.parse(JSON.stringify(s));syncChain=syncChain.catch(()=>{}).then(()=>pushTournamentStateNow(snap));return syncChain}async function updateMatch(id,patch){if(!(await isStaff()))throw new Error('Cal iniciar sessió com a organització');return req(`/rest/v1/matches?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{...patch,updated_at:new Date().toISOString()}})}
async function setupRealtime(){if(realtimeStarted)return;realtimeStarted=true;try{const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');client=mod.createClient(URL,KEY,{auth:{persistSession:false}});const s=session();if(s?.access_token)await client.auth.setSession({access_token:s.access_token,refresh_token:s.refresh_token});client.channel('campionat-live-2026').on('postgres_changes',{event:'*',schema:'public',table:'matches',filter:'tournament_id=eq.2026'},async()=>{await loadTournament();window.dispatchEvent(new CustomEvent('supabase:change',{detail:{table:'matches'}}))}).subscribe(status=>window.dispatchEvent(new CustomEvent('supabase:realtime',{detail:{status}})))}catch(e){realtimeStarted=false}}
async function init(){try{await hydratePortal();if(window.Torneig)await loadTournament();await setupRealtime()}catch(e){console.warn('Supabase init',e)}window.dispatchEvent(new CustomEvent('supabase:ready'));return true}
window.SupaSync={URL,KEY,init,session,signIn,signOut,isStaff,isAdmin,hydratePortal,loadTournament,createRegistration,reserveLunch,verifyPayment,pushTournamentState,updateMatch,req};
})();