(()=>{
const URL='https://mojwomfkgpvpwviqnptl.supabase.co';
const KEY='sb_publishable_UtAmoVy3jwRJe1ehoGJI_g_oBsh5jvl';
const SESSION_KEY='torneig2026_supabase_session';
const PORTAL_KEY='torneig2026_portal_data';
const STATE_KEY='torneig2026_state_v4';
let client=null, pairMap=new Map(), lastMatchSnapshot={};
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
const pairKey=p=>Array.isArray(p)?norm(p.filter(Boolean).join('|')):norm(p);
function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function token(){return session()?.access_token||KEY}
async function req(path,opt={}){const r=await fetch(URL+path,{method:opt.method||'GET',headers:{apikey:KEY,Authorization:`Bearer ${token()}`,'Content-Type':'application/json',Prefer:opt.prefer||'return=representation',...(opt.headers||{})},body:opt.body===undefined?undefined:JSON.stringify(opt.body)});if(!r.ok){const t=await r.text();throw new Error(t||`${r.status}`)}if(r.status===204)return null;const txt=await r.text();return txt?JSON.parse(txt):null}
async function signIn(email,password){const r=await fetch(URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.msg||d.error_description||'No s’ha pogut iniciar sessió');localStorage.setItem(SESSION_KEY,JSON.stringify(d));return d}
function signOut(){localStorage.removeItem(SESSION_KEY)}
async function isStaff(){try{return !!(await req('/rest/v1/rpc/is_staff',{method:'POST',body:{}}))}catch{return false}}
async function isAdmin(){try{return !!(await req('/rest/v1/rpc/is_admin',{method:'POST',body:{}}))}catch{return false}}
function localPortal(){try{return JSON.parse(localStorage.getItem(PORTAL_KEY)||'{}')}catch{return {}}}
function saveLocalPortal(s){localStorage.setItem(PORTAL_KEY,JSON.stringify(s))}
async function hydratePortal(){const p=localPortal();p.lunches=p.lunches||{};p.notices=p.notices||[];p.tournamentRegistrations=p.tournamentRegistrations||[];p.merchOrders=p.merchOrders||[];p.payments=p.payments||[];
 try{const cfg=(await req('/rest/v1/tournament_config?id=eq.2026&select=*'))?.[0];if(cfg){p.config={name:cfg.name,dates:cfg.dates,maxPairs:cfg.max_pairs,normalPrice:Number(cfg.normal_price),memberPrice:Number(cfg.member_price),mealPrice:Number(cfg.meal_price),bizum:cfg.bizum_instructions||'',phone:cfg.contact_phone||'',registrationOpen:cfg.registration_open,lunchOpen:cfg.lunch_open,merchOpen:cfg.merch_open,mvpOpen:cfg.mvp_open};p.dropboxUrl=cfg.dropbox_url||''}}
 catch{}
 try{const lunches=await req('/rest/v1/lunch_events?select=id,title,price,is_open');const res=await req('/rest/v1/lunch_reservations?select=id,lunch_id,full_name,bizum_name,payment_status,created_at');const byId={};(lunches||[]).forEach(x=>{byId[x.id]=x.title;p.lunches[x.title]=[]});(res||[]).forEach(x=>{const title=byId[x.lunch_id];if(title)p.lunches[title].push({id:x.id,name:x.full_name,bizumName:x.bizum_name,status:x.payment_status==='verified'?'verificat':x.payment_status==='bizum_sent'?'bizum_enviat':'pendent'})})}catch{}
 try{const ns=await req('/rest/v1/notices?published=eq.true&order=created_at.asc&select=id,title,body,notice_type,created_at');p.notices=(ns||[]).map(n=>({id:n.id,title:n.title,text:n.body,date:new Date(n.created_at).toLocaleString()}))}catch{}
 if(await isStaff()){
  try{const regs=await req('/rest/v1/tournament_registrations?order=created_at.asc&select=*');p.tournamentRegistrations=(regs||[]).map(r=>({id:r.id,p1:r.player1_name,p2:r.player2_name,member1:r.player1_type==='member',member2:r.player2_type==='member',amount:Number(r.amount),bizumName:r.bizum_name,status:r.payment_status==='verified'?'verificat':r.payment_status==='bizum_sent'?'bizum_enviat':'pendent'}))}catch{}
  try{const mo=await req('/rest/v1/merch_orders?order=created_at.asc&select=id,buyer_name,size,quantity,amount,bizum_name,payment_status,merch_products(name)');p.merchOrders=(mo||[]).map(o=>({id:o.id,buyer:o.buyer_name,product:o.merch_products?.name||'Merchandising',size:o.size,qty:o.quantity,total:Number(o.amount||0),bizumName:o.bizum_name,status:o.payment_status==='verified'?'verificat':o.payment_status==='bizum_sent'?'bizum_enviat':'pendent'}))}catch{}
  p.payments=[];(p.tournamentRegistrations||[]).forEach(r=>p.payments.push({dbType:'registration',dbId:r.id,kind:'Inscripció',ref:`${r.p1} / ${r.p2}`,bizumName:r.bizumName,amount:r.amount,status:r.status}));Object.values(p.lunches||{}).flat().forEach(r=>p.payments.push({dbType:'lunch',dbId:r.id,kind:'Dinar',ref:r.name,bizumName:r.bizumName,amount:Number(p.config?.mealPrice||10),status:r.status}));(p.merchOrders||[]).forEach(o=>p.payments.push({dbType:'merch',dbId:o.id,kind:'Merchandising',ref:`${o.buyer} · ${o.product}`,bizumName:o.bizumName,amount:o.total,status:o.status}));
 }
 saveLocalPortal(p);return p}
async function createRegistration(r){return req('/rest/v1/tournament_registrations',{method:'POST',body:{player1_name:r.p1,player2_name:r.p2,player1_type:r.member1?'member':'normal',player2_type:r.member2?'member':'normal',amount:r.amount,bizum_name:r.bizumName||null,payment_status:r.status==='bizum_enviat'?'bizum_sent':'pending',status:'pending'}})}
async function reserveLunch(meal,names,bizumName,sent){const events=await req(`/rest/v1/lunch_events?title=eq.${encodeURIComponent(meal)}&select=id`);if(!events?.length)throw new Error('Dinar no configurat');const gid=crypto.randomUUID();return req('/rest/v1/lunch_reservations',{method:'POST',body:names.map(n=>({lunch_id:events[0].id,full_name:n,reservation_group:gid,bizum_name:bizumName||null,payment_status:sent?'bizum_sent':'pending'}))})}
async function orderMerch(o){let prod=await req(`/rest/v1/merch_products?name=eq.${encodeURIComponent(o.product)}&select=id`);if(!prod?.length){if(!(await isStaff()))throw new Error('Producte encara no configurat');prod=await req('/rest/v1/merch_products',{method:'POST',body:{name:o.product,price:o.unitPrice||0,sizes:['XS','S','M','L','XL','XXL','Talla única']}})}return req('/rest/v1/merch_orders',{method:'POST',body:{product_id:prod[0].id,buyer_name:o.buyer,size:o.size,quantity:o.qty,amount:o.total,bizum_name:o.bizumName||null,payment_status:o.status==='bizum_enviat'?'bizum_sent':'pending'}})}
async function publishNotice(n){return req('/rest/v1/notices',{method:'POST',body:{title:n.title,body:n.text,notice_type:n.type||'info',published:true}})}
async function deleteNotice(id){return req(`/rest/v1/notices?id=eq.${id}`,{method:'DELETE'})}
async function saveConfig(c){return req('/rest/v1/tournament_config?id=eq.2026',{method:'PATCH',body:{name:c.name,dates:c.dates,max_pairs:c.maxPairs,normal_price:c.normalPrice,member_price:c.memberPrice,meal_price:c.mealPrice,bizum_instructions:c.bizum||null,dropbox_url:c.dropboxUrl||null,contact_phone:c.phone||null,registration_open:c.registrationOpen,lunch_open:c.lunchOpen,merch_open:c.merchOpen,mvp_open:c.mvpOpen,updated_at:new Date().toISOString()}})}
async function verifyPayment(p){if(!p?.dbId)return;const table=p.dbType==='registration'?'tournament_registrations':p.dbType==='lunch'?'lunch_reservations':'merch_orders';await req(`/rest/v1/${table}?id=eq.${p.dbId}`,{method:'PATCH',body:{payment_status:'verified'}})}
async function loadTournament(){if(!window.Torneig)return null;const players=await req('/rest/v1/players?select=id,full_name');const pairs=await req('/rest/v1/pairs?tournament_id=eq.2026&order=seed.asc&select=id,seed,player1_id,player2_id,color');const matches=await req('/rest/v1/matches?tournament_id=eq.2026&select=*');if(!pairs?.length||!matches?.length)return null;const pName=new Map((players||[]).map(x=>[x.id,x.full_name]));pairMap=new Map();const pairById=new Map();const arr=[];(pairs||[]).forEach(x=>{const p=[pName.get(x.player1_id)||'',pName.get(x.player2_id)||''];pairById.set(x.id,p);pairMap.set(pairKey(p),x.id);arr[(x.seed||1)-1]=p});const s=Torneig.freshState();s.pairs=arr.length?arr:s.pairs;(matches||[]).forEach(x=>{if(!s.matches[x.id])return;const m=s.matches[x.id];m.team1=x.team1_id?pairById.get(x.team1_id)||null:null;m.team2=x.team2_id?pairById.get(x.team2_id)||null:null;m.s1=x.score1||0;m.s2=x.score2||0;m.status=x.status==='final'?'final':x.status==='live'?'en joc':'pendent';m.time=x.scheduled_at||m.time;m.court=x.court||'Pista 1';lastMatchSnapshot[x.id]=JSON.stringify([x.team1_id,x.team2_id,x.score1,x.score2,x.status,x.scheduled_at,x.court])});localStorage.setItem(STATE_KEY,JSON.stringify(s));return s}
async function ensurePairMap(){if(pairMap.size)return;const players=await req('/rest/v1/players?select=id,full_name');const pName=new Map((players||[]).map(x=>[x.id,x.full_name]));const pairs=await req('/rest/v1/pairs?tournament_id=eq.2026&select=id,player1_id,player2_id');(pairs||[]).forEach(x=>pairMap.set(pairKey([pName.get(x.player1_id)||'',pName.get(x.player2_id)||'']),x.id))}
async function pushTournamentState(s){if(!(await isStaff()))return;await ensurePairMap();for(const id of Object.keys(s.matches||{})){const m=s.matches[id],row={team1_id:m.team1?pairMap.get(pairKey(m.team1))||null:null,team2_id:m.team2?pairMap.get(pairKey(m.team2))||null:null,score1:m.s1||0,score2:m.s2||0,status:m.status==='final'?'final':m.status==='en joc'?'live':'pending',scheduled_at:m.time||null,court:m.court||'Pista 1',updated_at:new Date().toISOString()},fp=JSON.stringify([row.team1_id,row.team2_id,row.score1,row.score2,row.status,row.scheduled_at,row.court]);if(lastMatchSnapshot[id]===fp)continue;await req(`/rest/v1/matches?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:row});lastMatchSnapshot[id]=fp}}
async function bootstrapTournament(s){if(!(await isStaff()))throw new Error('Cal iniciar sessió com a organització');const existingPlayers=await req('/rest/v1/players?select=id,full_name');const byName=new Map((existingPlayers||[]).map(x=>[norm(x.full_name),x.id]));for(const pair of s.pairs||[]){for(const name of pair||[]){if(!name||name.startsWith('Plaça lliure')||byName.has(norm(name)))continue;const ins=await req('/rest/v1/players',{method:'POST',body:{full_name:name}});byName.set(norm(name),ins[0].id)}}const existingPairs=await req('/rest/v1/pairs?tournament_id=eq.2026&select=id,seed');const bySeed=new Map((existingPairs||[]).map(x=>[x.seed,x.id]));for(let i=0;i<(s.pairs||[]).length;i++){const p=s.pairs[i],body={tournament_id:'2026',seed:i+1,player1_id:byName.get(norm(p?.[0]))||null,player2_id:byName.get(norm(p?.[1]))||null,status:'confirmed'};let pid=bySeed.get(i+1);if(pid)await req(`/rest/v1/pairs?id=eq.${pid}`,{method:'PATCH',body});else{const r=await req('/rest/v1/pairs',{method:'POST',body});pid=r[0].id;bySeed.set(i+1,pid)}pairMap.set(pairKey(p),pid)}for(const id of Torneig.allIds()){const m=s.matches[id],body={id,tournament_id:'2026',stage:m.stage,team1_id:m.team1?pairMap.get(pairKey(m.team1))||null:null,team2_id:m.team2?pairMap.get(pairKey(m.team2))||null:null,score1:m.s1||0,score2:m.s2||0,status:m.status==='final'?'final':m.status==='en joc'?'live':'pending',scheduled_at:m.time||null,court:m.court||'Pista 1'};await req(`/rest/v1/matches?on_conflict=id`,{method:'POST',prefer:'resolution=merge-duplicates,return=representation',body})}return loadTournament()}
async function setupRealtime(){try{const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');client=mod.createClient(URL,KEY,{auth:{persistSession:false}});const s=session();if(s?.access_token)await client.auth.setSession({access_token:s.access_token,refresh_token:s.refresh_token});client.channel('torneig-live').on('postgres_changes',{event:'*',schema:'public',table:'matches'},async()=>{await loadTournament();window.dispatchEvent(new Event('supabase:change'))}).on('postgres_changes',{event:'*',schema:'public',table:'notices'},async()=>{await hydratePortal();window.dispatchEvent(new Event('supabase:change'))}).on('postgres_changes',{event:'*',schema:'public',table:'lunch_reservations'},async()=>{await hydratePortal();window.dispatchEvent(new Event('supabase:change'))}).subscribe()}catch(e){console.warn('Realtime no disponible',e)}}
async function init(){let changed=false;try{const beforeP=localStorage.getItem(PORTAL_KEY),beforeS=localStorage.getItem(STATE_KEY);await hydratePortal();if(window.Torneig)await loadTournament();changed=beforeP!==localStorage.getItem(PORTAL_KEY)||beforeS!==localStorage.getItem(STATE_KEY);setupRealtime()}catch(e){console.warn('Supabase init',e)}window.dispatchEvent(new CustomEvent('supabase:ready',{detail:{changed}}));return changed}
window.SupaSync={URL,KEY,init,session,signIn,signOut,isStaff,isAdmin,hydratePortal,loadTournament,createRegistration,reserveLunch,orderMerch,publishNotice,deleteNotice,saveConfig,verifyPayment,pushTournamentState,bootstrapTournament,req};
})();
